version: '2.2'
services:
  app:
    env_file:
      - .env
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: './'
    ports:
      - 0.0.0.0:8000:80
    volumes:
      - ./:/app
